-- Migration: ajouter gestion de stock (articles) et table de liaison (utilisation par intervention)

-- Table des articles (stock)
CREATE TABLE IF NOT EXISTS articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nom text NOT NULL,
  description text,
  quantite numeric DEFAULT 0 NOT NULL,
  prix_unitaire numeric DEFAULT 0.0 NOT NULL,
  seuil_min numeric DEFAULT 0.0 NOT NULL,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_articles_nom ON articles (lower(nom));

-- Table pour enregistrer les articles utilisés dans une intervention
CREATE TABLE IF NOT EXISTS intervention_articles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  intervention_id bigint NOT NULL REFERENCES interventions(id) ON DELETE CASCADE,
  article_id bigint NOT NULL REFERENCES articles(id) ON DELETE RESTRICT,
  quantite_utilisee numeric NOT NULL DEFAULT 1,
  prix_unitaire numeric NOT NULL,
  created_by text,
  created_at timestamptz DEFAULT now()
);

-- Optionnel: historique de stock (audit)
CREATE TABLE IF NOT EXISTS historique_stock (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  article_id bigint NOT NULL REFERENCES articles(id) ON DELETE CASCADE,
  changement numeric NOT NULL,
  raison text,
  reference_intervention_id bigint,
  created_by text,
  created_at timestamptz DEFAULT now()
);
